### ISSUE TITLE
baked lightmap for metallic objects turns out black

### ISSUE THREAD

**Issue by LorenzWieseke** [Naxela/The_Lightmapper#10]
Taking a default cube and setting metallic up to one results in a black lightmap.

**Comment by Naxela** [comment]
By default Blender bakes objects black when they've metallic turned to 1, which makes sense since fully reflective surfaces doesn't receive much energy in itself. This isn't very artist friendly though, so I [added the option](https://github.com/Naxela/The_Lightmapper/commit/1753c0f150329658236cb4e27a372bdc48b3d50e) to clamp metallic surfaces to 0.99, which will always provide a little light to the surface:

![Clamp](https://user-images.githubusercontent.com/5429817/76126608-d569c780-5fff-11ea-9e4b-469de571544d.jpg)
