### ISSUE TITLE
'Clean Lightmaps' deletes all lightmaps in Lightmaps subfolder

### ISSUE THREAD

**Issue by kitaedesigns** [Naxela/The_Lightmapper#111]
'Clean Lightmaps' button deletes all lightmaps in Lightmaps subfolder. Is this right? I thought this button was for cleaning up the shader graphs? Sliversade's Aframe for Blender plugin describes the function of Clean Lightmaps as; 

"it's needed because the changes to the shaders can be incompatible with A-Frame"

https://github.com/silverslade/aframe_blender_exporter

**Comment by Naxela** [comment]
Hi, the behaviour is correct the actual lightmap files is also cleaned and removed from the lightmaps folder in order to prevent any python lockup when baking new lightmaps. In cases where you actually want to keep the lightmaps after cleaning them (perhaps if you want to return to the original shaders, but still keep the lightmaps for an external game engine), you can either turn on **keep bake files** which simply prevents the files from being deleted, or toggle **Don't apply materials** which will just go straight to the original shader setup:

![image](https://user-images.githubusercontent.com/5429817/117492736-4e511000-af72-11eb-9661-fb882cf942b0.png)

I hope this helps

**Comment by kitae22** [comment]
Ah I don't seem to have this button, am I on an older version? I'm version .5.0.0 currently.

![image](https://user-images.githubusercontent.com/23407511/117541193-b9d1c680-afe0-11eb-8684-e0823fc67716.png)

**Comment by Naxela** [comment]
Ah, I see - I guess I'm used to people just cloning or download straight from the master repository rather than the releases page. In any case, I've made a new release build (0.5.5): https://github.com/Naxela/The_Lightmapper/releases/tag/0.5.5

I hope this helps

**Comment by kitae22** [comment]
Ah ok I see! I will clone in the future, thanks!
