### ISSUE TITLE
No `Enable for Selection` button

### ISSUE THREAD

**Issue by LiamGallagher737** [Naxela/The_Lightmapper#153]
I'm watching [this](https://www.youtube.com/watch?v=DFRkJP2kE8M) video on the addon and it shows a button named `Enable for Selection` to add multiple objects at once, I can't seem to find this button so I assume it's been renamed or moved, if so where is it?

What I'm looking for
![image](https://user-images.githubusercontent.com/86995276/180387750-574811a9-8496-4ab8-88f7-df15503a10a2.png)

What I have, no `selection` dropdown
![image](https://user-images.githubusercontent.com/86995276/180387834-a199617a-8cf8-4c8d-87a3-1be9106ce101.png)

**Comment by Naxela** [comment]
Hi, and thanks for using the addon! - I guess ever since I changed it, it got a little harder to figure out. Instead of the enable for selection, you now have to select 'selection' in the drop down menu for the set (which is set to 'scene' now in your second image) and click the enable for scene button.

Hope it helps
