### ISSUE TITLE
Denoising Failed

### ISSUE THREAD

**Issue by LorenzWieseke** [Naxela/The_Lightmapper#5]
Hello,

first of all great add-on ! I think if this is will be pushed a bit it will drastically improve the hole process of baking !

I was experimenting with your newest version (added some code to link the baked lightmap node to a gltfSettings node to export it to glb and use it in three js) and figured that the denoising doesn't work anymore cause the denoised image can't be found. I tried to use the pipe from an older version but I don't really understand whats going on here. 

![image](https://user-images.githubusercontent.com/29607121/75594016-8663e580-5a87-11ea-9a2e-7461e1b8b5eb.png)

Old version just gives a black image, new version gives this error
![image](https://user-images.githubusercontent.com/29607121/75594119-f70b0200-5a87-11ea-8365-4b7397642319.png)

I couldn't find the file in the Lightmaps folder so I guess it wasn't saved. 

Could you help me ?

**Comment by Naxela** [comment]
Hi, 

Thanks for trying the addon - I presume you're testing out the newest version (cloned/zip) with Blender 2.81 and that you're using OIDN for denoising (latest OIDN version 1.10 from here: [https://github.com/OpenImageDenoise/oidn/releases](https://github.com/OpenImageDenoise/oidn/releases))?

The error you get usually occurs when there's something wrong with the denoising process, either because the baking process didn't store the raw non-denoised bakes, or because there's some permission restrictions from Windows

If you turn on the "Verbose" option under the denoising options, can you see if it provides some more information?:

![denoise_settings](https://user-images.githubusercontent.com/5429817/75604939-306e5c80-5ade-11ea-9925-214939a730b0.jpg)

The pipes from the new way just tells the denoiser that it should treat the input file as a lightmap for better denoising, there shouldn't be any difference - Unless you're using an older version of OIDN, as versions prior to 1.10 doesn't support the lightmapping mode, and might cause the message you got

By default the lightmaps should be located in a local folder called lightmaps - In your case, in your PBB/lightmaps folder, there should be some 32-bit HDR files:

![folder](https://user-images.githubusercontent.com/5429817/75604974-82af7d80-5ade-11ea-916b-8a961f5f4ec9.jpg)

I don't have a lot of experience with three.js, but I do plan on looking into extended compatibility to three.js and babylon.js in the future - currently, there's RGBM encoding for engines that doesn't support HDR textures

**Comment by LorenzWieseke** [comment]
Thanks a lot ! It the error occurred because I used an older version of the ODIN Denoiser, now it works like a charm.
