### ISSUE TITLE
Error during addon activation

### ISSUE THREAD

**Issue by cstfan** [Naxela/The_Lightmapper#50]
I try to install on blender 2.90.1 your addon in the version 0.4.4.3 and 0.4.3.4 but I have this error for both 

![image](https://user-images.githubusercontent.com/33685211/96954572-f251fd00-14f3-11eb-93a2-f7e0c4fe99d9.png)

For information, I already use the version 0.3.2.0 , it's great, thanks

**Comment by renderthings** [comment]
Hi cstfan,
I had the same issue installing version 4.28.
I fix it by installing firstly opencv on blender python via cmd (i'm on windows), then (using the preferences interface of Blender ) the others addons (Xatlas, texel Density Checker), and lastly Lightmapper addon.
Thanks Naxela for your addon! It seems very powerful 
Ciro

**Comment by Naxela** [comment]
Hi, and thanks for reporting the bug

Due to recent feature additions to atlas packing, there's been some dependency on OpenCV (CV2), but it's not supposed to be loaded if it's not present. I'll fix that bug soon. In the meantime, you can either install cv2 separately (as @renderthings  mentions), or you can download an older build an install OpenCV through the preferences:

![image](https://user-images.githubusercontent.com/5429817/97168280-758b8100-1788-11eb-87c8-2b9c84f257ac.png)

**Comment by cstfan** [comment]
I installed OpenCV via The Lightmapper 0.3 then I installed the 0.4.4.3 and version 0.0.5 of Xatlas, beyond not recognized. And now all is OK
Thanks
