### ISSUE TITLE
GPU baking whith CPU 

### ISSUE THREAD

**Issue by koloved** [Naxela/The_Lightmapper#72]
GPU CUDA baking with CPU is x10 times longer than without CPU

probably i should reported it to blender.org cause its blender issue

[https://prnt.sc/yp4b17](https://prnt.sc/yp4b17)

**Comment by Naxela** [comment]
I think this is a combined issue, as The Lightmapper automatically manages your tile size depending on the device you've selected for baking - CPU prefers smaller (32'ish) and GPU prefers larger (256'ish) for optimized baking. Plus, it's also very scene dependent, as there's overhead for the combined usage in smaller scenes, but it can be faster for larger scenes.

**Comment by Gpinchon** [comment]
I've witnessed this issue too, I could force GPU baking by setting tiles size in Render Properties -> Performance to 256px, that's rather strange...

**Comment by Naxela** [comment]
This sounds strange, as by default if using the GPU it should set the tile size to 256px by itself:
https://github.com/Naxela/The_Lightmapper/blob/1fda43d8052d87249567a33b14f7c072047b0aaf/addon/utility/cycles/prepare.py#L549-L554

These settings are set according to this from Blenderguru:
![image](https://user-images.githubusercontent.com/5429817/114085530-c82da500-98b1-11eb-865d-08f23907af8d.png)

I do think that the CPU might be "dragging" the GPU down in some cases, when both are activated when activated using either CUDA or OpenCL, but I haven't tested how much and which settings would be optimal in those cases, since you can have multiple combinations of any numbers of GPU's and maybe even CPU's:
![image](https://user-images.githubusercontent.com/5429817/114085723-04f99c00-98b2-11eb-9412-4ab22e44765c.png)

**Comment by Gpinchon** [comment]
Yeah, it was baking on the CPU, and after setting tiles to 256 it started baking on the GPU, but after restarting and re-opening Blender started baking on the CPU again, despite selecting my GTX 970 as the only CUDA device, I don't know what the heck is going on there... (I also started getting random freezes on some projects since last Blender update)
So this issue might be a Blender issue and not LightMapper's
