### ISSUE TITLE
Performance seems low?

### ISSUE THREAD

**Issue by rienheuver** [Naxela/The_Lightmapper#75]
Baking a scene with a few objects, medium quality, 1/1 resolution scale and 1024px textures can take a lot of time (GTX1060 6GB). It seems to me that it should be a lot faster? When I use cycles to inspect the scene in realtime it takes a couple of seconds to render the frame and when I do a full render it takes about a minute (including denoising).

So why does building the textures take so much longer? I've had builds take several hours with no special setups (I think).

**Comment by Naxela** [comment]
That's because when you render a scene it only renders the rays that originates from the camera and view to the visible elements for one texture (the actual render), whereas when baking - every texture for every object has to have the same amount of rays that is distributed all throughout the scene. So in other words, imagine you're rendering an image for each material for each object, which is pretty much why it takes longer.

Could you elaborate which render times you're getting and which Blender version? Just in case, there's a Blender bug somewhere

**Comment by rienheuver** [comment]
Blender version 2.83.12.
I just tried baking again, but this time the bakes seemed to be an incredible amount faster. The only things I can figure so far that I have changed:
- Started Blender from terminal instead of from app drawer (Gnome)
- Hit 'Clean Lightmaps' before starting the bake

Right now I'm baking my entire scene in 5 minutes, with several high-res (4k and 8k) textures and a total of 5 (emission) lights, which would have taken several hours before.

Any clue why it was so much slower before? If you want me to try some configurations to find potential bugs, just let me know. (And if it's because of the clean lightmaps, perhaps mention that somewhere in a tutorial or give a warning when someone starts a bake with the old lightmaps still attached.)

**Comment by Naxela** [comment]
That sounds quite strange, as internally when a baking starts it does pretty much the same as clean lightmaps function, and when baking it pretty much bakes in the RAM before saving so existing lightmaps or antivirus shouldn't be an issue either. 

But in general, unless it's 100's of 4K lightmaps, it shouldn't take more than a few minutes in general with moderate settings. 

I don't have access to Linux atm, but do you generally experience speed differences when using terminal vs. when using drawer?

**Comment by rienheuver** [comment]
I expected the plugin to clean the lightmaps before baking, so would be quite surprised if that would matter. Does it bake in the VRAM or the regular RAM? Next time I run into performance problems I can at least check my RAM and VRAM usages.

I just tried this a bit: looks like it uses the regular RAM and not VRAM. When I start the bake it easily takes 10GB (out of 16GB) of RAM while the VRAM doesn't get filled more than roughly 3GB (out of 6GB). So maybe I had too much RAM usages from other processes on my pc; too many chrome tabs probably... If that was the problem then perhaps increasing my swap-partition could make a big difference too.

I normally experience no performance difference whatsoever when starting from terminal or drawer, and that would really surprise me too.

**Comment by Naxela** [comment]
I'm not entirely sure, although I would think it renders to the VRAM if GPU is selected, and RAM if CPU is selected, otherwise I think it transfers to the RAM if VRAM is not enough, and HDD/SDD if RAM is not enough, although it sounds like both your VRAM and RAM should be more than enough in either case.

Anyway, the actual baking itself is powered by internal cycles functions, so I don't know if there's a potential Blender bug there, perhaps Linux specific as I haven't stumbled upon the same issue on Windows.

**Comment by rienheuver** [comment]
I render on GPU but it seems to use more RAM than VRAM, so not sure how it balances that. But if it's all blender anyway I guess there's not much to expect from you ;-). I'll close this for now and re-open if I run into anything that seems lightmapper-related.
