### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Cube.004_baked" not found'

### ISSUE THREAD

**Issue by Zundrium** [Naxela/The_Lightmapper#79]
First of all, please provide a way to donate for this amazing addon, when the other external UV unwrapping are implemented, this will probably be the main bake tool for Blender the upcoming years :)

Aside from that, when testing in multiple scenarios, these '_baked' not found errors keep popping up when switching lightmapper versions.

In the provided .blend file, I try to bake these multiple atlasses with manual xatlas groups and the 'copy existing' unwrap option for the atlas groups in the lightmapper. However, it keeps searching for the individual lightmaps in some way that I don't understand. It's mosty likely because I switched a lot between lightmapper versions because when I do it from scratch, there are no issues whatsoever.

If possible, could you take a look at what might be causing this issue? And if it's because of lightmap settings from an older version, is there a way to purge the settings on each individual object? 

[baketest.blend.zip](https://github.com/Naxela/The_Lightmapper/files/6142086/baketest.blend.zip)

**Comment by Zundrium** [comment]
It appears to have nothing to do with using different versions sadly. Just happens to pop up randomly once editing a scene. I'm trying to find out in which scenario it happens.

**Comment by Naxela** [comment]
Hi, thanks for trying out the addon!

Currently, I don't feel like I need donations as I mainly just develop for myself, but I really do appreciate people finding bugs so I can stabilize it more :)

As for the "_baked not found" error, it sounds strange and should mainly just happen if some postprocess stuff is happening (denoise, filtering or atlas postpacking).

If you wouldn't mind, if you turn on the "Verbose Output" option, the Blender console will display some more information about what goes on internally, and perhaps shed some light on when and why the error happens:

![image](https://user-images.githubusercontent.com/5429817/111299919-cd9c2480-8650-11eb-9f34-ed2e3282d685.png)

Thanks again!

**Comment by Zundrium** [comment]
[baketest2.blend.zip](https://github.com/Naxela/The_Lightmapper/files/6148424/baketest2.blend.zip)
Seems to have found the issue without looking at the debug log, brute forcing helps sometimes haha. It happens in this single cube scene once I tick the "Don't apply materials" box. Please take a look.

**Comment by Naxela** [comment]
Ah nice find 👍, I think I also found the culprit in the code - I never tried the headless (no material mode) along with the atlas options - The error seems to be caused by the headless mode taking the object name rather than the atlas name for the lightmap. I'll try to see if I can come up with a fix when I get home

If you don't mind me asking out of curiosity, since you're using the No material mode, are you using it for an external engine? Such as Three.js, babylon.js or something else?

**Comment by Zundrium** [comment]
Of course! I'm using it for a Babylon.js scene. 

When applying materials, metallic materials come out as black ignoring the albedo color. It also bakes the reflections in the "complete" lighting mode, which is something I wouldn't want when using an environment probe. So what I'm currently going for is a custom gltf loader extension to load the lightmap with custom gltf properties.

Aside from that, I want to convert all the images to the newly supported `.ktx2` extension which reduces both file size and in memory size. Which is perfect for a baked scene. 

PS: keep in mind that donations does not equal expectations, just appreciation for what you're sharing here :)

**Comment by Naxela** [comment]
Ok thanks, the reason I'm asking is that I'm currently looking into creating some tutorials in the wiki for these engines, but I sort of want to have an idea of how much work I need to put into tutorials based on the amount of users that are using The Lightmapper in a workflow. Currently, The Lightmapper have been a little Armory3D-centric.

As for the problem with metallic materials, it's generally a problem with lightmapped objects as fully metallic objects usually reflect the same amount of diffuse light in terms of contribution. The workaround is either playing around with the metallic clamping option or toggling skip material under the material properties.

By the way, not sure how exactly how environment probes works in Babylon.js, but The Lightmapper also has options to automatically work with CMFT to create radiance HDR's and extracted coefficients for spherical harmonics using the probes in Blender, should especially be good if working with interior environments

As for .ktx2 I'll have to look into that, as I can imagine it would work well for other engines too if the lightmaps could be exported as that extension, since space is becoming quite a big issue with these lightmaps

**Comment by Zundrium** [comment]
Hey thanks for the explanation. The fact that The Lightmapper denoises, filters and encodes is more than enough for me. Since the GLTF standard does not support lightmaps out of the box, the only way to use it at the moment is with a custom workaround until there's an official extension for this.

The reason I'm going for a seperate texture in the custom properties of the GLTF file, is because Babylon.js does support lightmaps, so it's just a matter of linking the property to the Babylon.js feature and you're done.

The way I use environment probes is very similar, by using CMFT to create a 128x128 `.dds` file from an .hdr completely unrelated to the Blender scene, and then converting it to a Babylon.js specific `.env` file which has reduced file size.

`.ktx2` is part of the GLTF standard and it's possible to convert `.png` or `.jpeg` images using their [KTX Software](https://github.com/KhronosGroup/KTX-Software) tools. It's not yet possible to use them in Blender so I can imagine it being a hard time to include in The Lightmapper.

**Comment by Zundrium** [comment]
@Naxela Alright, tested out the master and it works perfectly now. Thanks a lot!
