### ISSUE TITLE
Hashed shadow rendered as opaque

### ISSUE THREAD

**Issue by Gpinchon** [Naxela/The_Lightmapper#93]
It seems like hashed shadows get rendered as opaque shadows and that light transmission is not taken into account for light baking when using Principled BSDF materials

**Comment by Naxela** [comment]
Hi,

Can you provide some examples of what you're trying to achieve? For some effects to be "activated" you need to use the high preset or higher, and this includes transmission and caustics. Due to the difference in light path bounce types as well as the samples (there aren't a lot of bounces in general at lower quality settings):

Ground truth (Cycles render):

![GT_Alpha](https://user-images.githubusercontent.com/5429817/114281277-d01a5000-9a3d-11eb-8e7a-324e6a2e824e.png)

With interior previz setting:

![Quality_InteriorPreview](https://user-images.githubusercontent.com/5429817/114281303-e58f7a00-9a3d-11eb-95df-30ee87536fdf.png)

With high settings: 

![Quality_High](https://user-images.githubusercontent.com/5429817/114281306-e7f1d400-9a3d-11eb-881e-e1f978e818b4.png)

Some goes for transmission for the principled materials:

Without transmission (on high quality):

![Transmission_1](https://user-images.githubusercontent.com/5429817/114281321-f809b380-9a3d-11eb-9c36-844ab339e0c3.jpg)

With transmission (on high quality):

![Transmission_0](https://user-images.githubusercontent.com/5429817/114281320-f6d88680-9a3d-11eb-8fb3-c75200683616.jpg)


Additionally, you can always set the light path bounces manually by selecting the custom option in the quality settings, and setting the light bounces you wish, and the lightmapper should adhere to it:

![image](https://user-images.githubusercontent.com/5429817/114281342-27b8bb80-9a3e-11eb-8969-5ef5dfcf4d29.png)

![image](https://user-images.githubusercontent.com/5429817/114281347-31422380-9a3e-11eb-935e-be4b6170138f.png)


It reminds me, that this is one of those countless areas I should probably document a little better

**Comment by Gpinchon** [comment]
Okay ! I was not aware of that, I was using previz & medium settings...
Your answer is quite complete and helpful you could almost copy-paste it in the doc as it is 😊
